/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTRootView.h"
#import "RCTViewManager.h"
#import "JPFPSStatus.h"
#import "RNAppGlobals.h"
#import "Example1ViewController.h"
#import "Example2ViewController.h"
#import "MenuManager.h"
#import "MenuTableViewController.h"

@implementation AppDelegate
@synthesize bridge,frostedViewController;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */

//   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"ReactNativeRollingExamples"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation
                                 moduleProvider:nil
                                  launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  
  Example1ViewController *example1=[[Example1ViewController alloc] init];
  MenuTableViewController *menuController = [[MenuTableViewController alloc] initWithStyle:UITableViewStylePlain];
  frostedViewController = [[REFrostedViewController alloc] initWithContentViewController:example1 menuViewController:menuController];
  frostedViewController.direction = REFrostedViewControllerDirectionLeft;
  frostedViewController.liveBlurBackgroundStyle = REFrostedViewControllerLiveBackgroundStyleLight;
  frostedViewController.liveBlur = YES;
  
  MenuManager *drawerManager = [MenuManager sharedInstance];
  drawerManager.contentViewController =example1;
  drawerManager.menuViewController = menuController;
  self.window.rootViewController = drawerManager.drawerViewController;
  [self.window makeKeyAndVisible];
  [[RNAppGlobals sharedInstance] setAppBridge:rootView.bridge];

  [[JPFPSStatus sharedInstance] openWithHandler:^(NSInteger fpsValue) {
      NSLog(@"fpsvalue %@",@(fpsValue));
  }];
  return YES;
}

@end
